import Foundation

/// Runs MediaMTX on this Mac: the RTMP server the cameras publish into.
///
/// A camera cannot be told to stream anywhere clever. The control protocol
/// carries a destination and nothing more, so something has to be listening at
/// that destination. On a show with nodes that is the node. With no nodes — on
/// the bench, or with one camera on the desk — it is this.
///
/// It is also where the switcher publishes its four output lanes, which is what
/// Vahana then pulls: Vahana is always an RTMP client, so a server has to sit in
/// between no matter how small the setup is.
public final class MediaMTXServer: @unchecked Sendable {

    public enum ServerError: Error, CustomStringConvertible {
        case binaryNotFound
        case launchFailed(String)

        public var description: String {
            switch self {
            case .binaryNotFound:
                return "mediamtx not found — install it with: brew install mediamtx"
            case .launchFailed(let why):
                return "mediamtx failed to start: \(why)"
            }
        }
    }

    private let rtmpPort: Int
    private let apiPort: Int
    private let configuredBinary: String
    private var process: Process?

    public private(set) var isRunning = false

    public init(rtmpPort: Int = 1935, apiPort: Int = 9997, binaryPath: String = "") {
        self.rtmpPort = rtmpPort
        self.apiPort = apiPort
        self.configuredBinary = binaryPath
    }

    // MARK: - Lifecycle

    public func start() throws {
        guard process == nil else { return }
        guard let binary = locateBinary() else { throw ServerError.binaryNotFound }

        let configURL = try writeConfig()

        let task = Process()
        task.executableURL = URL(fileURLWithPath: binary)
        task.arguments = [configURL.path]
        // Anything it decides to write goes beside its config, never into
        // whatever directory the app happened to be launched from.
        task.currentDirectoryURL = configURL.deletingLastPathComponent()

        // MediaMTX logs to stdout. Routing it into our own log means a failure to
        // bind the port, or a config it dislikes, shows up in the app rather than
        // vanishing into a pipe nobody reads.
        let pipe = Pipe()
        task.standardOutput = pipe
        task.standardError = pipe
        pipe.fileHandleForReading.readabilityHandler = { handle in
            let chunk = handle.availableData
            guard !chunk.isEmpty, let text = String(data: chunk, encoding: .utf8) else { return }
            for line in text.split(separator: "\n") where !line.isEmpty {
                Log.info("mediamtx", String(line))
            }
        }

        task.terminationHandler = { [weak self] finished in
            self?.isRunning = false
            self?.process = nil
            if finished.terminationStatus != 0 {
                Log.error("mediamtx", "exited with status \(finished.terminationStatus)")
            }
        }

        do {
            try task.run()
        } catch {
            throw ServerError.launchFailed(error.localizedDescription)
        }

        process = task
        isRunning = true
        Log.info("mediamtx", "listening for RTMP on :\(rtmpPort)")
    }

    public func stop() {
        process?.terminate()
        process = nil
        isRunning = false
    }

    // MARK: - Where it lives

    private func locateBinary() -> String? {
        var candidates: [String] = []
        if !configuredBinary.isEmpty { candidates.append(configuredBinary) }
        candidates += ["/opt/homebrew/bin/mediamtx", "/usr/local/bin/mediamtx", "/usr/bin/mediamtx"]
        return candidates.first { FileManager.default.isExecutableFile(atPath: $0) }
    }

    private func writeConfig() throws -> URL {
        let directory = AppPaths.support
        try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)

        let url = directory.appendingPathComponent("mediamtx.yml")
        try config.write(to: url, atomically: true, encoding: .utf8)
        return url
    }

    /// Deliberately minimal: this instance receives cameras and re-publishes the
    /// programme. It records nothing — recording belongs to the nodes, and a Mac
    /// quietly filling its own disk during a show is the last thing anyone needs.
    private var config: String {
        """
        # Generated by 4i Studio. Edits here are overwritten on every launch.

        logLevel: info
        logDestinations: [stdout]

        rtmp: yes
        rtmpAddress: :\(rtmpPort)

        api: yes
        apiAddress: 127.0.0.1:\(apiPort)

        hls: no
        webrtc: no
        srt: no
        rtsp: no

        # MoQ is on by default in v1.20 and wants a TLS keypair, which it writes
        # into the working directory. Launched from Finder that is "/", the write
        # fails, and MediaMTX shuts everything down including RTMP — so the app
        # worked from a terminal and not from the Dock.
        moq: no

        # The Orah opens all four of its RTMP connections at once and sends the
        # publish command on them much later — measured at over 30s on a camera
        # that was otherwise healthy. Whatever is still silent when this expires
        # gets cut, and the camera answers by tearing down and restarting the
        # whole set, which looks exactly like broken hardware. The original Orah
        # setup ran nginx-rtmp, which is far more forgiving here.
        readTimeout: 120s
        writeTimeout: 120s
        writeQueueSize: 2048

        pathDefaults:
          source: publisher
          record: no

        paths:
          all_others:

        """
    }
}
